### ISSUE TITLE
Fashion Net

### ISSUE THREAD

**Issue by ankitkumar8** [liuziwei7/fashion-detection#1]
This does not implement the FashionNet in DeepFashion: Powering Robust Clothes Recognition and Retrieval with Rich Annotations and doesn't work. Also, the parameters of layers are not well explained in the paper? can't really see how can research community reproduce the results in the paper :(

**Comment by liuziwei7** [comment]
This repository only contains the fashion detection module described in "DeepFashion: Powering Robust Clothes Recognition and Retrieval with Rich Annotations". We plan to release other modules of DeepFashion (e.g. fashion recognition and retrieval) in the near future.

**Comment by pbamotra** [comment]
Any updates on the release of fashionnet code?
